
spring:  application:    name: 'loja'
    
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    # Adiciona a url do eureka, do discovery service.
    service-url:      defaultZone: http://localhost:8761/eureka

