
spring:  application:    name: 'loja'
    
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    # Adiciona a url do eureka, do discovery service.
    service-url:      defaultZone: http://localhost:8761/eureka

# Configura o security para dizer qual endpoint rest ele vai chamar para
# buscar as informações do usuário, nesse caso, o servidor de autenticação.
security:
  oauth2:
    resource:
      # Ele vai validar o token, e buscar as informações do usuário.
      user-info-uri: http://localhost:8088/user

# Como alguns services estão com o pool de threads ativo e preciso interceptar os
# requests no feign client para adicionar o token de autenticação do usuário para
# poder consultar os demais serviços, preciso habilitar o compartilhamento do
# contexto de segurança do hystrix, pois o service que consome está com o pool de threads
# ativo, dessa forma o service é executado numa thread diferente da que recebeu a
# requisição, dessa forma preciso habilitar esse compartilhamento para poder
# recuperar o token do usuário logado e poder repassar ao feign client.
hystrix:  shareSecurityContext: true
