
spring:  application:    name: 'loja'
    
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    # Adiciona a url do eureka, do discovery service.
    service-url:      defaultZone: http://localhost:8761/eureka

# Configura o security para dizer qual endpoint rest ele vai chamar para
# buscar as informações do usuário, nesse caso, o servidor de autenticação.
security:
  oauth2:
    resource:
      # Ele vai validar o token, e buscar as informações do usuário.
      user-info-uri: http://localhost:8088/user
